name: latest

on:
  push:
    paths-ignore:
      - '*.md'

  workflow_dispatch:

env:
  DOCKER_BASE_NAME: ghcr.io/rechon-chat/bot

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}

      - name: Build & Push
        uses: docker/build-push-action@v2
        env:
          DOCKER_BUILDKIT: 1
        with:
          push: true
          tags: ${{ env.DOCKER_BASE_NAME }}:latest
          cache-from: ${{ env.DOCKER_BASE_NAME }}:latest
          build-args: BUILDKIT_INLINE_CACHE=1
